build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - repo_checks/submodule_check.sh
    - git submodule update --remote
    - .travis/install.sh
    - .travis/script.sh pulp3-source-centos8-fips